
namespace eval ::ttk::dialog::file {   
    ::msgcat::mcset de Location					Ort
    ::msgcat::mcset de Filter					Dateityp
    ::msgcat::mcset de Name						Name
    ::msgcat::mcset de Size						Größe
    ::msgcat::mcset de Date						Änderungsdatum
    ::msgcat::mcset de Permissions				Berechtigungen
    ::msgcat::mcset de Owner					Besitzer
    ::msgcat::mcset de Group					Gruppe
    ::msgcat::mcset de Folder					Ordner
    ::msgcat::mcset de Sorting					Sortierung
    ::msgcat::mcset de Reverse					Umgekehrt
    
    ::msgcat::mcset de {Short View}				{Listenansicht}
    ::msgcat::mcset de {Detailed View}			{Detailansicht}
    ::msgcat::mcset de {Show Hidden Files}		{Verborgene Dateien anzeigen}
    ::msgcat::mcset de {Separate Folders}		{Seitenleiste}
    ::msgcat::mcset de {By Name}				{Nach Namen}
    ::msgcat::mcset de {By Date}				{Nach Datum}
    ::msgcat::mcset de {By Size}				{Nach Größe}
    ::msgcat::mcset de {Folders First}			{Ordner zuerst}
    ::msgcat::mcset de {New Folder}				{Neuer Ordner}
    ::msgcat::mcset de {Create new folder in}	{Neuer Ordner erstellen in}
    
    ::msgcat::mcset de {File "%s" already exists. Do you want to overwrite it?}		{Datei "%s" existiert bereits. Soll sie überschrieben werden?}
    ::msgcat::mcset de {File "%s" does not exist.}									{Datei "%s" existiert nicht.}
    ::msgcat::mcset de {Cannot change to the directory "%s". Permission denied.}	{Kann nicht in das Verzeichnis "%s" wechseln. Keine Berechtigung.}
}

