
namespace eval ::ttk::dialog::file {   
    ::msgcat::mcset en Location
    ::msgcat::mcset en Filter
    ::msgcat::mcset en Name
    ::msgcat::mcset en Size
    ::msgcat::mcset en Date
    ::msgcat::mcset en Permissions
    ::msgcat::mcset en Owner
    ::msgcat::mcset en Group
    ::msgcat::mcset en Folder
    ::msgcat::mcset en Sorting
    ::msgcat::mcset en Reverse
    
    ::msgcat::mcset en {Short View}
    ::msgcat::mcset en {Detailed View}
    ::msgcat::mcset en {Show Hidden Files}
    ::msgcat::mcset en {Separate Folders}
    ::msgcat::mcset en {By Name}
    ::msgcat::mcset en {By Date}
    ::msgcat::mcset en {By Size}
    ::msgcat::mcset en {Folders First}
    ::msgcat::mcset en {New Folder}
    ::msgcat::mcset en {Create new folder in}
    
    ::msgcat::mcset en {File "%s" already exists. Do you want to overwrite it?}
    ::msgcat::mcset en {File "%s" does not exist.}
    ::msgcat::mcset en {Cannot change to the directory "%s". Permission denied.}
}


