
namespace eval ::ttk::dialog::file {   
    ::msgcat::mcset sv Location                 Plats
    ::msgcat::mcset sv Filter                   Filter
    ::msgcat::mcset sv Name                     Namn
    ::msgcat::mcset sv Size                     Storlek
    ::msgcat::mcset sv Date                     Datum
    ::msgcat::mcset sv Permissions              Behörigheter
    ::msgcat::mcset sv Owner                    Ägare
    ::msgcat::mcset sv Group                    Grupp
    ::msgcat::mcset sv Folder                   Mapp
    ::msgcat::mcset sv Sorting                  Sortering
    ::msgcat::mcset sv Reverse                  Omvänd
    
    ::msgcat::mcset sv {Short View}             {Enkel vy}
    ::msgcat::mcset sv {Detailed View}          {Detaljerad vy}
    ::msgcat::mcset sv {Show Hidden Files}      {Visa dolda filer}
    ::msgcat::mcset sv {Separate Folders}       {Mappar separat}
    ::msgcat::mcset sv {By Name}                {Efter namn}
    ::msgcat::mcset sv {By Date}                {Efter datum}
    ::msgcat::mcset sv {By Size}                {Efter storlek}
    ::msgcat::mcset sv {Folders First}          {Mappar först}
    ::msgcat::mcset sv {New Folder}             {Ny mapp}
    ::msgcat::mcset sv {Create new folder in}   {Skapa ny mapp i}
    
    ::msgcat::mcset sv {File "%s" already exists. Do you want to overwrite it?}   {Filen "%s" finns redan. Vill du skriva över den?}
    ::msgcat::mcset sv {File "%s" does not exist.}                                {Filen "%s" finns ej.}
    ::msgcat::mcset sv {Cannot change to the directory "%s". Permission denied.}  {Kan ej skifta till mappen "%s". Ej tillräcklig behörighet.}
}



