#TREE_NODE_CLASS_GIF[0..-1]=<<EOS
#R0lGODlhFAAUAMT/AAAAAP////Pz/fr6/vz8/9zd+tvc+QAK2A4X2hMc2xcg
#3Bwl3CAp3TM74DhA4TxE4U9W5FNa5WZs6HR56nl+64uQ7Zmd752h8Kyv8q2w
#8tHT+OPk++jp+9Hb/////wAAACwAAAAAFAAUAEAFh2AnjmRpHigaHNAQUNx6
#yEA3B7iMJlKUorWDw9FoBIrFxY9myzmfOaBtCXVKDxGLNqDFFAg4xey6dE1U
#A9VV9tAdFAHN7xCc2+31u54+TbnnTAcVVQEZBhcIY3yAKC0BAgFigUuOZzFq
#iykROGcqHJhBK4NucBtzoX4/DHGnfXt4ALGys7S0IQA7
#EOS

W_MAX_GIF[0..-1]=<<EOS
R0lGODlhCwAJAIAAAP///////yH5BAEKAAEALAAAAAALAAkAAAITDI4Ylrmw
4puSwmpovXdryTVKAQA7
EOS

W_NORM_GIF[0..-1]=<<EOS
R0lGODlhCwAJAIAAAP///////yH5BAEKAAEALAAAAAALAAkAAAIUjIFpm7oB
XjwtTlghk2j7r3HNUwAAOw==
EOS

#TREE_NODE_CLASS_GIF[0..-1]=<<EOS
#R0lGODlhEAAQAIABADGvJP///yH+EUNyZWF0ZWQgd2l0aCBHSU1QACH5BAEK
#AAEALAAAAAAQABAAAAIojI+pq+APHQLM0EPjC9fy9mEfNE5l2aFeZmYbK6Zr
#q8FeldZRxfdIAQA7
#EOS


#TREE_NODE_CLASS_GIF[0..-1]=<<EOS
#R0lGODlhEAAQALP/AAAAAP8A/wD//wCZmcDAwP//AJmZAJkAAJmZmQAAAAAA
#AAAAAAAAAAAAAAAAAAAAACH5BAEAAAQALAAAAAAQABAAAARDkEgCpr0SlIqv
#Lls3fYVhcGMGlqcXcJoJIDQNBMcBtxJC4ToLiuCjBEXEFDK5tBQpzRpAMBRN
#B4OqR4DVYgDZplISAQA7
#EOS

#TREE_NODE_CLASS_GIF[0..-1]=<<EOS
#R0lGODlhEgATAKEBAAAAAP///////////yH+EUNyZWF0ZWQgd2l0aCBHSU1Q
#ACH5BAEKAAIALAAAAAASABMAAAIulI+py+0GopxRgYCzBlb7wCXUGCLXl5XH
#iYJd64rk9LYqBMdmfgsz/QgKh8RGAQA7
#EOS

TREE_NODE_CLASS_GIF[0..-1]=<<EOS
R0lGODlhEgAQAOeGAAAnGaAAAHYQC8MAAMcAAM0AAMsBAXobG6QRBABAJNYE
CPMAAMYOBP8AAP8EBAxNI7sfH6QrAIc1DK4rK1JLFsYoLu0fJRBlEv8gILQ3
NwByLss8AE1gG8xCAMJKANFGANVHAFVtGm5oDrdVAG9rE29sJSCHGXFxG9RP
TwCRNP9FRQCTMwCVNQCWMyuOFQCaNXZ2QOVbIACeMwCeNPdSVQCfNxWhNOlf
X3OLDP9nAP9pAP9qAPxhYv9tAKaKAv9wAEqjIf9xAOx0HimsMv9oaP9qai2u
MyqyM/94AP9ubv9vb+x2dv9yckSyKDC3NlOuLP90dOaHCOSMAP94eP97e/+L
AP+EhN6dA/+Ghv+VAGHBQ2LIMWLJLf+hAf6Tk/+VlfKnFGrNMWfONmjPNGvP
Nf+rAGfTOGTTRGHXM/+uAGzVNnDVNmHZO3LXNf+zAP+1AHTZPv+2Bv+/AGjm
SXvhSH7iR//DAP/FDv/IAP/JAIPnS4zoYoTwev/bAP/cAP/eAJH3XZT4YpX/
Yp3/qrr/mf//AP//////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
/////////////////////yH+EUNyZWF0ZWQgd2l0aCBHSU1QACH5BAEKAP8A
LAAAAAASABAAAAjFAP8JHEiwoMGDAmMgRHHjQEEhcaIUnLDEChQiGQaC+YPn
TZcRAiF4+UJFSREmFQTcKeTHTpo0ZTz8M4AhCZYpPCwg4HAlTx88brIg+fCP
QAMHKmgokKBlDhAfaeRU2RGkw78BDbIygMFHUB0zTXBI0dEDyQaBBbKWGEQI
EB0ya46I+BEEBMEAC06w2RNIjxgjLEjkiHAwBBoucM7YaPGCAsJ/JtSMCTNk
hYwaAB7/c7GljZEZKRJoFnjhiRMNows+SM1aYEAAOw==
EOS




#TREE_NODE_MODULE_GIF[0..-1]=<<EOS
#R0lGODlhEAAQAIABADGv4P///yH+EUNyZWF0ZWQgd2l0aCBHSU1QACH5BAEK
#AAEALAAAAAAQABAAAAIojI+pq+APHQLM0EPjC9fy9mEfNE5l2aFeZmYbK6Zr
#q8FeldZRxfdIAQA7
#EOS

TREE_NODE_MODULE_GIF[0..-1]=<<EOS
R0lGODlhEgAQAOeLABYYRBkaPiEiWiUnXyQndCgpVScoaigpYCYoeiUofS0u
ZCstdiwtdystfCwugy0vfC4why8xgC8xii8yiTEyhjEzjzI1jDM2mTc5dTc5
ejQ4nTU4nDc5lTY5nzo8ijg8njw+gDo9nz0/hz5AhD9BgT5BkzxApkNEgkJE
h0RGi0NFnURHi0ZIkEZImkdJoEpMhkpNnktNpE1PjUtNrE5Qo09RqFJUnFhZ
nFpbklhaplpdq2RntmRnu2Zpp2hqtmptwW5ws3JzrnJ0wHV4v3V3yXd5yHh6
yXl7xH1+unt9z4OF1ISF1ISG1oWH1YWH2YaIzYaI0oaI1oaI2IaI2YeJ1IeJ
1YiK14uN1I2P1o2P35CRyI2Q44+S2JCS35KT15GT25GT4JOVzpOV0pOV25OV
5pWX0paY2JeZ4pmb2Zqc3J6g3p+g3J6g4KCh3aSm3qeo26mq36mr4qus5q6w
5rS167y998LD6cPE6cTF6cXG6sXG68jJ7MnK7svM8M3O8M7P7M/Q79XW8NfX
89na8dvc8uLi9+Hi/+fo9+vr+ezs+fLy+v//////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
/////////////////////yH+EUNyZWF0ZWQgd2l0aCBHSU1QACH5BAEKAP8A
LAAAAAASABAAAAjEAP8JHEiwoMGDAn8gBHKkQEEvfrQUfCGGzRcnMgbiUTSo
Dx0cAkfImWPmipUtIBQYWpQo0B09dU78azDjiZoxRkoQWPGmECJCedyAQfHv
QYcNPHwk8BAmjQ4kewChgdKFxD8GJj5ccBDkD582TXb0KEMFCxkMAheE0EBD
0CE7a6pMaWHjzJQUBAVMiLEEjp04RVQgyEFkwEEWUpJwGWJBAoUDCP+JYBJF
iQsIHCJEFphBSJYaFQxsJngDBoDRBQOgXi0wIAA7
EOS

TREE_NODE_DEF_GIF[0..-1]=<<EOS
R0lGODlhEAAQAIcAAHMhc3spe3sxe3sxhAD/AIwxjJQ5lJw5nIxCjJRKlJRS
lKVKraVSpa1Srb1rvb1zvc5jztZr1oycrZylra21rbW9rc6Mzt6c3uec5++U
7++c7/+c/+et5++l7++97/+t/8bGrc7OrdbWrefnre/nrff3rQAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAACH5BAMAAAQALAAAAAAQABAAAAhrAAkIHEiwoMGD
CA1aSFjQAoeFDAlY8PAhA8SBJURQkCCRw4cNGywmZOCgA8gNGBIQKEFCBAgK
EwgsiFBygwYFARA2iBDhwQUEB3KuHBGiQkwCOyMIOFBAqE4IAQw4TdhgAICI
A69i3coVa0AAOw==
EOS

#SYNCICON20_GIF[0..-1]=<<EOS
#R0lGODlhEAAQAKECAKDj9uztjf///////yH+EUNyZWF0ZWQgd2l0aCBHSU1Q
#ACH5BAEKAAIALAAAAAAQABAAAAIplH+By6HtooSyrmqvQ5tyZkTgyADmCCBm
#WrLG2q6y+85zbNPHSS76UgAAOw==
#EOS

SYNCICON20_GIF[0..-1]=<<EOS
R0lGODlhEAAQAKUoACBuDSBvDiBwDiRyEACAACmLEEGGMkWHNUqKPEikJk2j
Kl2zM4PKXX3YR37ZR4rfV43tR5LuUJXuVZrvXKPwa6bxca3yfLzroLHzgrjz
jbn0jsj2p8z3rc73ss/3s976y+L60OL60eX71eX71u/85fL96vT97vf+8v//
////////////////////////////////////////////////////////////
/////////////////////////////////yH+EUNyZWF0ZWQgd2l0aCBHSU1Q
ACH5BAEKAD8ALAAAAAAQABAAAAZvwJ9wSCwOC8ikkVgglUynwpL5CY2kQmSx
cNlwPNgCSIQVJiwYgCbM6TAMQsBjAvgB6tlMRhCHQPBMFBV4AH6ARxEShA5/
R1IFEA14BwqGQgQQkBALCEMBDY0/mH4NA0V3Q6OhU6INrpKsdnezsVNBADs=
EOS

CLEAR_GIF[0..-1]=<<EOS
R0lGODlhEAAQALMAAAAAAAD/AIQAAISEAISEhNbWzv8AAP//AP//////////
/////////////////////yH5BAEAAAEALAAAAAAQABAAAAQ+MMhJq53AmLzF
5aAAWKAGiKRpohWQhWN7HDCJAAh9xhSO3IeBy/b7AYSfIqJA4LUKP6aTVJBe
WsOrdsulRAAAOw==
EOS

D_STEP_INTO_GIF[0..-1]=<<EOS
R0lGODlhEAAQAIQSAE9ZXzpDX1aJtGd8laJtFfzjn/zlp6t4Gfzos7OAG/3s
wP3wz/7129bAff745/7679K6d9nFj///////////////////////////////
/////////////////////////yH+EUNyZWF0ZWQgd2l0aCBHSU1QACH5BAEK
AB8ALAAAAAAQABAAAAVC4CeOZGmeaFombBuhySPPCQS3SeMk6pgwvN4nsQim
WopW6oBoNg8qgmFKEBIKVZNgMBCMsp9t9wMIBACn8lnIPoUAADs=
EOS

D_NEXT_GIF[0..-1]=<<EOS
R0lGODlhEAAQAIQVAE9ZXzpDX1aJtGd8laJtFfzjn/zlp6t4Gfzos/3swLOA
G/3wz/712+rYp9nFj76OLtjEiu3gvv7679K6d8WXOv//////////////////
/////////////////////////yH+EUNyZWF0ZWQgd2l0aCBHSU1QACH5BAEK
AB8ALAAAAAAQABAAAAVQ4CeOZGmeaGo6lOK6lLM+kWTb0TORzsM0L1eD8YCM
FD9FSTFUihQL5zI6OiQOS1fiJSKYDgWEuIBNEQqGglf1Oa9LgsFAMHqXAIEA
gM3vj0IAOw==
EOS


D_STEP_OUT_GIF[0..-1]=<<EOS
R0lGODlhEAAQAIQaAE9ZXzpDX6NuFlaJtGd8laVwF/zlpaZyF/znrahzF/3q
t6p2GP3twqx4Gf7wza56Gf7z19bAfdnFj698Gv724dK6d7B+Gv746bJ/GrOA
G////////////////////////yH+EUNyZWF0ZWQgd2l0aCBHSU1QACH5BAEK
AB8ALAAAAAAQABAAAAVN4CeOZGmeaKqSWbaOGIKplWVfiIVKE+X7iMnpAYk8
iIYHquFofBoGJ2rBWHwW1lRCkXh9DojDaUAgDEQFQ0FENn8AgQBgJBjB5d58
KQQAOw==
EOS

D_RESUME_GIF[0..-1]=<<EOS
R0lGODlhEAAQAKUrABZrRRhtRnm6XXi6XhluRxtvSG21Xm21XxxwSR9yS2Gv
YWGwYB9zSyBySyJ2UE2nZk2nZU2mZSJ2Tid6UlircViqcVerclirciV4USp9
VoO9gIO9gYO+gSl6Uy6AV5PFhpPFhyx+Vix/VjKDWqLLi6PLii+AVzSEXKzP
jjKDWTOEXP//////////////////////////////////////////////////
/////////////////////////////////yH+EUNyZWF0ZWQgd2l0aCBHSU1Q
ACH5BAEKAD8ALAAAAAAQABAAAAZbwJ9wSCwaj8ik8XRSKYcnFCo1eo5I2JLJ
lPR8vh8QKCQ6ZjRozWbN6XSKE4p8XrFYLhii48F/QCAREBISRQkKhwoLCwwN
RwUGBwcGCAhJAQIDAQRPAJ1Pn6BGQQA7
EOS

D_QUIT_GIF[0..-1]=<<EOS
R0lGODlhEAAQAMQAAOgwOOg4QOhASOhIUPBocMAQIOggMMgoONBgcMhQQMhY
SPiwqMhAOLg4OOhQUPB4ePioqNiYmP///wAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAABIALAAAAAAQABAAAAVUoCSOZGme
aGpGSuu6UZksdF0nMuTsvAPhJEZkQCwOIoySUMBsCpClxgNArQIeSVKDYOh6
DYRG6TC1Uh+HUiESaLsDkYIaQq/X5SREYc/nI1SAgRIhADs=
EOS

OFF_GIF[0..-1]=<<EOS
R0lGODlhCgALAIABAPsKLP///yH+EUNyZWF0ZWQgd2l0aCBHSU1QACH5BAEK
AAEALAAAAQAKAAoAAAITRI4Hm7qMnnSyvmAhrm22/YVBAQA7
EOS

ON_GIF[0..-1]=<<EOS
R0lGODlhCgALAOMPAF+XAGCXAGGYAFuaAF+ZAGOYAGGZAGSZAGWZAGKaAGOb
AGSbAGGcAGibAGOdAP///yH+EUNyZWF0ZWQgd2l0aCBHSU1QACH5BAEKAA8A
LAAAAAAKAAoAAAQv8MlJaWJVCrFIZUICLMKkBATIKMljMIngAMIREg1RSElC
KAoGZjIAIUqV3jAjiAAAOw==
EOS

FREEZE_GIF[0..-1]=<<EOS
R0lGODlhCgAKAIABAPn7NP///yH+EUNyZWF0ZWQgd2l0aCBHSU1QACH5BAEK
AAEALAAAAAAKAAoAAAIShB2ph5oM3GMyQHkX1cfl2TkFADs=
EOS


#PROCESS_KILL_GIF=<<EOS
#R0lGODlhEAAQALMAAAAAAP////wCBNwCBKwCBHQCBAQCBKSipHR2dNze3P//
#/wAAAAAAAAAAAAAAAAAAACH5BAEAAAoALAAAAAAQABAAAARSUEllqq0zG8G7
#IEZGCUNpluC0neyQri0LbkdiJ/Ux2EdRCYlScLjb+TYJRJE4PAoQzCXOuawG
#B05cMVfEVggxlo8CDntV5dZYQyi432vR5ZKJAAA7
#EOS